# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ecd732366a7415a479d7e24f42674e5f88d91543d11ac42e3cb1a6dbebf1b455e3b200fbef58f3594e4d11268ba6856c626cbb7f33fa271e92d1d48d8b7bb5e

test:
  secret_key_base: c38c29f2e14983cee60bd648a6dea16aab82b3724db6ba927446b42f5c83273a7d0e2bf8789bd8355dbcb025995149f791636302f42c01cbeec3fb4412390101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
